server:
  port: 8080
spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost/student?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
  mvc:
    static-path-pattern: /static/**
mybatis:
  type-aliases-package: cn.bdqn.entity
  mapper-locations: mapper/*Mapper.xml